### ISSUE TITLE
Layout:page id=4

### ISSUE THREAD

**Issue by Lebeau09** [standapp-org/fuer-gesunde-familien#39]
prod: https://www.fuer-gesunde-familien.ch/index.php?id=4
dev: https://dev.fuer-gesunde-familien.ch/hier-unterzeichnen

**Prod**

![pd2](https://github.com/user-attachments/assets/9572d336-3af6-40cf-b982-ae097985ca69)

**Dev**

![dev2](https://github.com/user-attachments/assets/cfb00af5-5270-4869-aa6f-d56b8d9837ed)

**Comment by compaoreh338** [comment]
@Lebeau09  a retester
